name: cron job

on:
  schedule:
    - cron: 0 0 * * *


jobs:
  cron-job:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
          ref: testing

    - name: set up node
      uses: actions/setup-node@v1

    - name: install dependencies
      run: npm install

    - name: run
      run: |
        node runner.js Grade >> logger.txt
        node runner.js Marks >> logger.txt
        if [ -d "html/Grade" ]; then 7z u -t7z html-zip/Grade.7z ./html/Grade; fi
        if [ -d "html/Marks" ]; then 7z u -t7z html-zip/Marks.7z ./html/Marks; fi

    - name: push changes
      uses: stefanzweifel/git-auto-commit-action@v4.4.1
      with:
        branch: testing
        commit_message: added changes by action
        commit_user_name: Saransh Bhatia
        commit_user_email: saranshbht@gmail.com

    - name: send failure notification
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: du-results
        status: FAILED
        color: danger
